Hidebutton
ajayshans/moviequest pull request #30
Opened 2023-10-05 10:57 UTC by Julian-A-Mort

Primarily a jss update,

2023-10-05 11:02 UTC, ajayshans commented on index.html
> -        <section>
@Julian-A-Mort any reason why this section was removed? Looks like we would lose the youtube preview if we do

2023-10-05 11:07 UTC, ajayshans commented on index.html
> +        <p id="messageDisplay"></p>
I think if we replace lines 120-122 here with the red lines 110-122 it should fix the problem

2023-10-05 11:08 UTC, ajayshans requested changes
Ensure we retain youtube preview by replacing green lines 120-122 in index.html file with red lines 110-122

2023-10-06 06:00 UTC, ajayshans commented
Hi @Julian-A-Mort similar comment to Bea's pull request following the above changes. Once above changes have been made, could you please run the below:
```
git pull origin main
<resolve any conflicts>
```
Final output should look like the codebase in main branch + your new changes and the only js file that should remain is script.js

2023-10-07 03:16 UTC, Julian-A-Mort commented
Change made to include youtube display. Please check again...

2023-10-07 03:21 UTC, ajayshans approved these changes

2023-10-07 03:26 UTC, itsbbea approved these changes

2023-10-07 03:26 UTC, merged